server:
  host: 0.0.0.0
  port: 8228
  log_level: info

# Optional: override or add agents by key using dotted paths module:Class
# Example:
# agents:
#   custom_graph: bioagents.agents.graph_agent:GraphAgent
agents: {}
